version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/alisdairrankine/chip8
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: bash test.sh
      - run: bash <(curl -s https://codecov.io/bash)